random_ints_1m.tgz:
	curl -o $@ https://storage.googleapis.com/ann-filtered-benchmark/datasets/random_ints_1m.tgz

random_float_1m.tgz:
	curl -o $@ https://storage.googleapis.com/ann-filtered-benchmark/datasets/random_float_1m.tgz

random_keywords_1m.tgz:
	curl -o $@ https://storage.googleapis.com/ann-filtered-benchmark/datasets/random_keywords_1m.tgz
all: random_ints_1m.tgz random_float_1m.tgz random_keywords_1m.tgz
